menu:
  Home: /
  Archives: /archives
  Tags: /tags

# duoshuo comment
duoshuo: false
duoshuo_name:

# disqus comment
disqus: true
disqus_shortname: ochronuscom

# google analytics
googleTrackId: UA-69017316-6

